name: Android Debug Release

on:
  push:
    branches:
      - testing-ci-cd  # Adjust this if you want to build on a different branch

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk

    - name: Get current date
      id: get_date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: debug-${{ steps.get_date.outputs.date }}  # Use the current date to create a unique tag
        release_name: Debug Release ${{ steps.get_date.outputs.date }}
        draft: false
        prerelease: true

    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This is the upload URL returned from the create_release step
        asset_path: ./app/build/outputs/apk/debug/app-debug.apk # Update this to match the path of your APK file
        asset_name: app-debug.apk
        asset_content_type: application/vnd.android.package-archive